### ISSUE TITLE
使用 rclone 和 k8s job 一键迁移历史文件到 MinIO

### ISSUE THREAD

**Issue by 2eha0** [2eha0/notes#1]
## 背景
私有云中使用 MinIO 作为文件服务，已经通过 Helm Chats 的方式实现一键部署到 k8s，在此前有一套陈旧的自建文件系统还在使用，需要将其中的历史文件一键迁移到 MinIO 中，希望可以在部署 MinIO 时自动完成，并且希望可以做到多次运行幂等。

## 迁移脚本准备
迁移文件有很多工具可以用，我最终选择的是 [rclone](https://rclone.org/)，原因是 rclone 的 copy 可以跳过已经复制的文件，这样即使多次执行迁移脚本也不会每次都全量复制。

安装好 rclone 之后需要准备一个配置文件，填入 MinIO 服务的基本信息之后就可以使用 rclone 连上 MinIO 了
```
[local]
type = s3
provider = Minio
access_key_id = <MINIO_AK>
endpoint = <MINIO_ENDPOINTER>
```
Rclone 的配置文件中可以不填密码，密码可以设置环境变量 `RCLONE_S3_SECRET_ACCESS_KEY` 来指定
```bash
export RCLONE_S3_SECRET_ACCESS_KEY=<MINIO_SECRET>
rclone lsd local:bucket # 查看 bucket 中的目录
```
迁移命令推荐使用 `copy` 而不是 `sync`，后者会删除目标地址内多余的文件，对于我们幂等的要求而言是不需要的，而 `copy` 命令并不会删除文件
```bash
rclone copy /source-path local:dest-path -P # 加上 -P 可以查看进度
```
到这一步我们的迁移脚本已经可以用了，接下来要把运行脚本的行为变得自动化

## 创建 k8s job
我需要创建一个 job 来运行迁移脚本，脚本可以放在 configmap 里面然后通过 volumns 挂载到镜像里，这个 job 可以借助 Helm 的 [Chart Hooks](https://helm.sh/docs/topics/charts_hooks/) 来实现在安装后自动运行。

先写个 Hello world 测试一下
```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-migrate-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded # 删除上一次运行的 job
spec:
  ttlSecondsAfterFinished: 86400 # delete job after 1 day
  template:
    spec:
      containers:
        - name: bash-runner
          image: registry.****.net/library/upgrade-tool:v1.1.2 # 这里我已经提前把 rclone 安装到镜像里了
          imagePullPolicy: IfNotPresent
          command: [sh, -c]
          args: ["echo 'hello' && sleep 5000"] # 这里 sleep 是为了让 job 保留下来，方便我们查看 job 运行日志
      restartPolicy: Never
  backoffLimit: 4
```
通过 `helm install` 或者 `helm upgrade` 命令来测试这个 job，如果没有报错可以查看 pod 日志来检查运行结果，这里不再赘述

经过测试后这样运行 job 是没问题的，接下来就要把我们的迁移脚本送到镜像里去，可以将脚本写到 configmap 中
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-migrate-job
  namespace: {{ $.Release.Namespace }}
data:
  rclone.conf: |
    [local]
    type = s3
    env_auth = true
    provider = Minio
    access_key_id = minioadmin
    endpoint = {{ .Values.MINIO_ENDPOINTER }}
  clone.sh: |
    mkdir -p /root/.config/rclone
    cp /usr/share/shell/rclone.conf /root/.config/rclone/rclone.conf
    export RCLONE_S3_SECRET_ACCESS_KEY={{ .Values.MINIO_PASSWORD }}
    rclone lsd local:bucket
    rclone copy /source-path local:bucket -P
    exit 0
```
然后修改 job chart，将 configmap 和宿主机上的文件目录挂载到镜像中
```yml
          args: ["sh /usr/share/shell/clone.sh && sleep 1"] # 在这里运行 clone.sh，可以改大 sleep 保留日志
          volumeMounts:
          - mountPath: /source-path
            name: source-storage
          - mountPath: /usr/share/shell
            name: shared-shell 
      volumes:
      - name: source-storage
        hostPath:
          path: /data/source # 宿主机文件目录
      - name: shared-shell
        configMap:
          name: minio-migrate-job # configmap 文件
```
这样就算完成了，可以使用 `mc` 工具来检验是否迁移成功，多次运行几次也没有问题，rclone 会跳过已经存在的文件，第二次运行会非常快结束。
